name: Android CI

on:
  push:
    branches: [ "master", "Phase1" ]
  pull_request:
    branches: [ "master", "Phase1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean
    - name: Build DebugAPK
      run: ./gradlew assembleDebug
    - name: uploadAPK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
